name: publish

on:
  release:
    types: [published]

env:
  GHCR_ORG: "The-Water-Museum"
  CONTAINER_NAME: "steamcmd"

jobs:
  publish-steamcmd-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GHCR Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: downcase REPO
        run: |
          echo "REPO=${GHCR_ORG,,}" >>${GITHUB_ENV}
      - name: Build and publish image
        run: |
          docker build . --tag ghcr.io/${{ env.REPO }}/${{ env.CONTAINER_NAME }}:${{ github.event.release.tag_name }}
          docker run ghcr.io/${{ env.REPO }}/${{ env.CONTAINER_NAME }}:${{ github.event.release.tag_name }}
          docker push ghcr.io/${{ env.REPO }}/${{ env.CONTAINER_NAME }}:${{ github.event.release.tag_name }}